apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: workspaces.workspace.che.eclipse.org
spec:
  group: workspace.che.eclipse.org
  names:
    kind: Workspace
    plural: workspaces
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            devfile:
              properties:
                apiVersion:
                  description: 'APIVersion defines the versioned schema of this representation
                    of an object. Servers should convert recognized schemas to the
                    latest internal value, and may reject unrecognized values. More
                    info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
                  type: string
                commands:
                  items:
                    properties:
                      actions:
                        items:
                          properties:
                            command:
                              type: string
                            tool:
                              description: The actual action command-line string
                              type: string
                            type:
                              description: Describes tool to which given action relates
                              type: string
                            workdir:
                              description: Describes action type
                              type: string
                          required:
                          - command
                          - tool
                          - type
                          type: object
                        type: array
                      attributes:
                        description: List of the actions of given command. Now the
                          only one command must be specified in list; but there are
                          plans to implement supporting multiple actions commands.
                        type: object
                      name:
                        description: Additional command attributes
                        type: string
                    required:
                    - name
                    type: object
                  type: array
                kind:
                  description: 'Kind is a string value representing the REST resource
                    this object represents. Servers may infer this from the endpoint
                    the client submits requests to. Cannot be updated. In CamelCase.
                    More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
                  type: string
                metadata:
                  type: object
                projects:
                  description: Description of the predefined commands to be available
                    in workspace
                  items:
                    properties:
                      name:
                        type: string
                      source:
                        properties:
                          location:
                            type: string
                          type:
                            description: Project's source location address. Should
                              be URL for git and github located projects, or; file://
                              for zip.
                            type: string
                        required:
                        - location
                        - type
                        type: object
                    required:
                    - name
                    - source
                    type: object
                  type: array
                tools:
                  description: Description of the projects, containing names and sources
                    locations
                  items:
                    properties:
                      endpoints:
                        items:
                          properties:
                            attributes:
                              properties:
                                discoverable:
                                  description: 'Identifies server as secure or non-secure.
                                    Requests to secure servers will be authenticated
                                    and must contain machine token - default: false'
                                  type: boolean
                                path:
                                  description: Defines protocol that should be used
                                    for communication with endpoint. Is used for endpoint
                                    URL evaluation"
                                  type: string
                                protocol:
                                  description: 'Identifies endpoint as accessible
                                    by its name. - default: false'
                                  type: string
                                public:
                                  type: boolean
                                secure:
                                  description: 'Identifies endpoint as workspace internally
                                    or externally accessible - default: true'
                                  type: boolean
                              type: object
                            name:
                              type: string
                            port:
                              description: The endpoint name
                              format: int64
                              type: integer
                          required:
                          - name
                          - port
                          type: object
                        type: array
                      env:
                        description: Describes dockerimage tool endpoints
                        items:
                          properties:
                            name:
                              type: string
                            value:
                              description: The environment variable name
                              type: string
                          required:
                          - name
                          - value
                          type: object
                        type: array
                      id:
                        description: The environment variables list that should be
                          set to docker container
                        type: string
                      image:
                        description: Describes the tool FQN
                        type: string
                      local:
                        description: Specifies the docker image that should be used
                          for tool
                        type: string
                      localContent:
                        description: Describes location of Kubernetes list yaml file.
                          Applicable only for 'kubernetes' and; 'openshift' type tools
                        type: string
                      memoryLimit:
                        description: Inlined content of a file specified in field
                          'local'
                        type: string
                      mountSources:
                        description: 'Describes memory limit for the tool. You can
                          express memory as a plain integer or as a; fixed-point integer
                          using one of these suffixes: E, P, T, G, M, K. You can also
                          use the; power-of-two equivalents: Ei, Pi, Ti, Gi, Mi, Ki'
                        type: boolean
                      name:
                        description: Describes whether projects sources should be
                          mount to the tool. `CHE_PROJECTS_ROOT`; environment variable
                          should contains a path where projects sources are mount
                        type: string
                      selector:
                        description: Describes the name of the tool. Should be unique
                          per tool set.
                        type: object
                      type:
                        description: Describes the objects selector for the recipe
                          type tools. Allows to pick-up only selected; items from
                          k8s/openshift list
                        type: string
                      volumes:
                        description: Describes type of the tool, e.g. whether it is
                          an plugin or editor or other type
                        items:
                          properties:
                            containerPath:
                              type: string
                            name:
                              type: string
                          required:
                          - containerPath
                          - name
                          type: object
                        type: array
                    required:
                    - name
                    - type
                    type: object
                  type: array
              required:
              - tools
              type: object
            started:
              type: boolean
          required:
          - started
          - devfile
          type: object
        status:
          type: object
  version: v1beta1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
