apiVersion: workspace.che.eclipse.org/v1beta1
kind: Workspace
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: workspace-sample
  namespace: crds
spec:
  started: false
  devfile:
    apiVersion: 0.0.1
    metadata:
      name: chectl 
    projects:
      - name: chectl
        source:
          type: git
          location: 'https://github.com/che-incubator/chectl.git'
    tools:
      - name: theia-ide
        type: cheEditor
        id: org.eclipse.che.editor.theia:1.0.0
      - name: exec-plugin
        type: chePlugin
        id: che-machine-exec-plugin:0.0.1
      - name: fortune
        type: chePlugin
        id: org.eclipse.che.samples.container-fortune:0.0.1
      - name: xml
        type: chePlugin
        id: redhat.vscode-xml:0.3.0
    commands:
      - name: build
        actions:
          - type: exec
            tool: theia-ide
            command: yarn
            workdir: /projects/chectl
      - name: test
        actions:
          - type: exec
            tool: theia-ide
            command: yarn test
            workdir: /projects/chectl
